# Generated by Django 4.0.3 on 2022-03-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='mybad'),
            preserve_default=False,
        ),
    ]
